In [31]:
import numpy as np
from scipy.linalg import expm

phi1 = 1.3758  	
phi2 = -0.3922

phi=np.array([phi1,phi2])
print("arma coefficients :", phi)

if phi2>0:
    print("problem: phi2 must be <0")

coeffarma = [-phi2, -phi1, 1]

roots = np.roots(coeffarma)
print("roots :", roots)

lambda_vals = -np.log(roots) 
print("lambda :", lambda_vals)

def coeffcarma(eigenvalues):
    [lam1,lam2] = eigenvalues.copy()
    a1=-(lam1+lam2)
    a2=lam1*lam2
    return [a1,a2]

a=coeffcarma(lambda_vals)
a= np.array([float(x) for x in a])

if phi1-2*np.exp(-a[0]/2)<0:
    print("problem: phi1 must be >= 2*exp(-a1)/2")

print("carma AR coefficients :", a)

theta=-0.1304

print("arma MA coefficients :", theta)

arma coefficients : [ 1.3758 -0.3922]
roots : [2.47964368 1.02826045]
lambda : [-0.90811487 -0.02786849]
carma AR coefficients : [0.93598337 0.02530779]
arma MA coefficients : -0.1304


In [4]:
import numpy as np

def buildcompanion(a):
    p = len(a)
    A = np.zeros((p,p))
    for i in range(p-1):
        A[i,i+1] = 1

    A[p-1,:] = -np.array(a[::-1])
    return A

buildcompanion(a)

array([[ 0.        ,  1.        ],
       [-0.02530779, -0.93598337]])

In [5]:
import numpy as np
from scipy.linalg import solve_continuous_lyapunov

def buildsigma(coefcarma):
    A=buildcompanion(coefcarma)
    p=len(coefcarma)
    ep=np.zeros((p,1))
    ep[p-1,0]=1

    Q=ep@ep.T

    sigma=solve_continuous_lyapunov(A,-Q)
    return sigma
buildsigma(a)

array([[2.11080246e+01, 4.44089210e-16],
       [3.20923843e-16, 5.34197528e-01]])

In [6]:
def m0(phi,a):
    A=buildcompanion(a)
    [phi1,phi2]=phi
    sigma=buildsigma(a)
    M0=((1+phi1**2+phi2**2)*np.identity(2)+(2*phi1*phi2-2*phi1)*expm(A)-2*phi2*expm(2*A))@sigma
    return M0

def m1(phi,a):
    A=buildcompanion(a)
    [phi1,phi2]=phi
    sigma=buildsigma(a)
    M1=((-phi1+phi1*phi2)*np.identity(2)+(1-phi2+phi1**2+phi2**2)*expm(A)+(-phi1+phi1*phi2)*expm(2*A)-phi2*expm(3*A))@sigma
    return M1

def m(phi,a,theta):
    M0=m0(phi,a)
    M1=m1(phi,a)
    return M0-((1+theta**2)/theta)*M1

In [7]:
M=m(phi,a,theta)

b0=(1/(2*M[0,0]))*(-(M[0,1]+M[1,0])+np.sqrt((M[0,1]+M[1,0])**2-4*M[0,0]*M[1,1]))

print("carma MA coefficient :", b0)
print("carma AR coefficients :", a)


carma MA coefficient : 1.7863102779209301
carma AR coefficients : [0.93598337 0.02530779]


In [25]:
import numpy as np
from scipy.linalg import expm

phi1 =2.045764 	
phi2 = -1.3459
phi3= 0.2943


phi=np.array([phi1,phi2,phi3])
print("arma coefficients :", phi)

coeffarma = [-phi3,-phi2, -phi1, 1]

roots = np.roots(coeffarma)
print("roots :", roots)

lambda_vals = -np.log(roots) 
print("lambda :", lambda_vals)

def coeffcarma(eigenvalues):
    [lam1,lam2,lam3] = eigenvalues.copy()
    a1=-(lam1+lam2+lam3)
    a2=lam1*lam2+lam2*lam3+lam1*lam3
    a3=-lam1*lam2*lam3
    return [a1,a2,a3]

a=coeffcarma(lambda_vals)
a= np.array([float(x) for x in a])

print("carma AR coefficients :", a)

theta=-0.8973


arma coefficients : [ 2.045764 -1.3459    0.2943  ]
roots : [1.77364662+0.40765928j 1.77364662-0.40765928j 1.02593136+0.j        ]
lambda : [-0.59877739-0.22591875j -0.59877739+0.22591875j -0.02560084-0.j        ]
carma AR coefficients : [1.22315562 0.44023206 0.01048543]


C:\Users\gabri\AppData\Local\Temp\ipykernel_32080\338262834.py:28: ComplexWarning: Casting complex values to real discards the imaginary part
  a= np.array([float(x) for x in a])


In [26]:
buildcompanion(a)

array([[ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [-0.01048543, -0.44023206, -1.22315562]])

In [27]:
buildsigma(a)

array([[ 1.10469475e+02,  1.74574646e-15, -9.46993222e-01],
       [ 1.80217833e-15,  9.46993222e-01, -1.32023154e-16],
       [-9.46993222e-01, -1.06397747e-17,  4.16896773e-01]])

In [28]:
def m0(phi,a):
    A=buildcompanion(a)
    [phi1,phi2,phi3]=phi
    sigma=buildsigma(a)
    M0=((1+phi1**2+phi2**2+phi3**2)*np.identity(3)+(-2*phi1+2*phi1*phi2+2*phi2*phi3)*expm(A)+(-2*phi2+2*phi1*phi3)*expm(2*A)+(-2*phi3)*expm(3*A))@sigma
    return M0

def m1(phi,a):
    A=buildcompanion(a)
    [phi1,phi2,phi3]=phi
    sigma=buildsigma(a)
    M1=((-phi1+phi1*phi2+phi2*phi3)*np.identity(3)+(1-phi2+phi1**2+phi2**2+phi1*phi3+phi3**2)*expm(A)+(-phi1+phi1*phi2+phi2*phi3-phi3)*expm(2*A)+(-phi2+phi1*phi3)*expm(3*A)+(-phi3)*expm(4*A))@sigma
    return M1

def m(phi,a,theta):
    M0=m0(phi,a)
    M1=m1(phi,a)
    return M0-((1+theta**2)/theta)*M1

In [ ]:
M=m(phi,a,theta)
b0=(1/(2*M[0,0]))*(-(M[0,1]+M[1,0])+np.sqrt((M[0,1]+M[1,0])**2-4*M[0,0]*M[1,1]))

print((1/(2*M[0,0]))*(-(M[0,1]+M[1,0])))
print((M[0,1]+M[1,0])**2-4*M[0,0]*M[1,1])

print("carma MA coefficient :", b0)
print("carma AR coefficients :", a)

1.4532189013490985e-15
-0.12208942455077049
carma MA coefficient : nan
carma AR coefficients : [1.22315562 0.44023206 0.01048543]


C:\Users\gabri\AppData\Local\Temp\ipykernel_32080\1463044553.py:2: RuntimeWarning: invalid value encountered in sqrt
  b0=(1/(2*M[0,0]))*(-(M[0,1]+M[1,0])+np.sqrt((M[0,1]+M[1,0])**2-4*M[0,0]*M[1,1]))
